var a;
a = 10;
a = 20.5;
var b = '10';
console.log('NUMBER DATA TYPE');
console.log(parseInt(b));
console.log(typeof a, a);
var c;
c = 'honey';
console.log("STRING DATA TYPE");
console.log(typeof c, c);
console.log("BOOLEAN DATA TYPE");
var d = false;
console.log(!d, typeof d);
var e;
e = ['a', 'b', 'c', 'd'];
console.log("ARRAY DATA TYPE");
console.log(e, typeof e);
var f;
f = [1, 2, 3, 4, 5];
console.log(f);
var g = f.filter(function (num) { return num >= 2; });
console.log(g);
var h = f.reduce(function (acc, num) { return acc + num; });
console.log("sum of array " + h);
console.log("ENUM DATA TYPE");
var i;
i = [10, 20];
console.log(i);
var days;
(function (days) {
    days[days["Sunday"] = 0] = "Sunday";
    days[days["Monday"] = 1] = "Monday";
    days[days["Tuesday"] = 2] = "Tuesday";
    days[days["Wednesday"] = 3] = "Wednesday";
    days[days["Thursday"] = 4] = "Thursday";
    days[days["Friday"] = 5] = "Friday";
    days[days["Saturday"] = 6] = "Saturday";
})(days || (days = {}));
;
var j = days.Sunday;
console.log(typeof i, j);
var edays;
(function (edays) {
    edays[edays["Sunday"] = 1] = "Sunday";
    edays[edays["Monday"] = 2] = "Monday";
    edays[edays["Tuesday"] = 3] = "Tuesday";
    edays[edays["Wednesday"] = 4] = "Wednesday";
    edays[edays["Thursday"] = 5] = "Thursday";
    edays[edays["Friday"] = 6] = "Friday";
    edays[edays["Saturday"] = 7] = "Saturday";
})(edays || (edays = {}));
;
var k = edays.Sunday;
console.log(typeof edays, k, edays);
console.log(edays['Sunday']);
